name: Android Build with Third-Party Action

on: 
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build APK
        uses: sparkfabrik/android-build-action@v1.0.0
        with:
          project-path: .
          output-path: my-app.apk
          gradle-task: assembleDebug
      
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: my-app.apk
