name: Build Android App

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      
      - name: Build debug APK
        run: ./gradlew assembleDebug
      
      - name: List files for debugging
        run: find . -name "*.apk"
      
      - name: Save APK
        uses: actions/upload-artifact@v2
        with:
          name: debug-apk
          path: ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
